### ISSUE TITLE
Decide on the layout of public facing website

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc.github.io#1]
_Note: this issue related to a public facing website that is for informational purposes only. This website is not meant to serve as a portal to data. Additionally, all the pages will live here in this repository, which means that you can submit pull requests or open issue to suggest updates to the website_

Below, I have one suggestion for what pages should be on the website and how they will be arranged. Is anything missing? Does anyone have a better suggestion?

```
Home
About
    Consortium overview
    Executive summary
    Onboarding process
    Related efforts
Who we are
    PIS
    Teams 
    Data Stewards 
    NIH
    advisory board
Milestones 
Deliverables
News
    Blog
    newsletter
    press releases 
Contact
```

**Comment by charlesreid1** [comment]
This should be addressed by private-www and public-www
