### ISSUE TITLE
decide on website theme

### ISSUE THREAD

**Issue by raynamharris** [dcppc/dcppc.github.io#2]
In addition to Issue #1, we also the to chose a "theme", which will determine how the website looks and feels. 

We can use any of the [pelican themes](http://pelicanthemes.com/) or [jekyll themes](http://jekyllthemes.org/). Or we can use a more custom website as a template. I quite like The [Carpentries website](https://carpentries.org/).

Suggestions? Thoughts?

**Comment by charlesreid1** [comment]
public/internal websites now covered by private-www and public-www
